[package]
name = "caw_patches"
version = "0.5.0"
description = "Collection of common patches for the caw synthesizer framework"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
homepage = "https://github.com/gridbugs/caw.git"
repository = "https://github.com/gridbugs/caw.git"
documentation = "https://docs.rs/caw_patches"
edition = "2024"

[dependencies]
caw_modules = { version = "0.5", path = "../modules" }
caw_builder_proc_macros = { version = "0.2", path = "../builder-proc-macros" }
caw_core = { version = "0.6", path = "../core" }
caw_utils = { version = "0.5", path = "../utils" }
