[package]
name = "caw_widgets"
version = "0.4.0"
edition = "2024"
description = "Graphical widgets for the caw synthesizer framework"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
homepage = "https://github.com/gridbugs/caw.git"
repository = "https://github.com/gridbugs/caw.git"
documentation = "https://docs.rs/caw_widgets"

[dependencies]
anyhow = "1.0"
sdl2 = { version = "0.38", features = ["gfx"] }
line_2d = "0.5"
coord_2d = "0.3"
midly = "0.5"
caw_computer_keyboard = { version = "0.4", path = "../computer-keyboard" }
caw_keyboard = { version = "0.4", path = "../keyboard" }
caw_sdl2 = { version = "0.1", path = "../sdl2" }
caw_window_utils = { version = "0.1", path = "../window-utils" }
caw_persist = { version = "0.1", path = "../persist" }
itertools = "0.14"
log = "0.4"
serde = { version = "1.0", features = ["serde_derive"] }

[dev-dependencies]
env_logger = "0.11"
caw_midi_udp_client = { path = "../midi-udp-client" }
caw_midi = { path = "../midi" }
clap = { version = "4", features = ["derive"] }

[[example]]
name = "knob_demo"
